### ISSUE TITLE
Agregando icono en html

### ISSUE THREAD

**Issue by fannybecerravera** [fannybecerravera/scl-2018-05-bc-core-am-datadashboard#12]
Hola Mayra hay le agregue el icono a los botónes, para que actualices tu repositorio con el pull origin master y lo puedas visualizar.

**Comment by fannybecerravera** [comment]
Mayra se me había olvidado le adelgace el margen a los botones sentí que visualmente se veía un poco tosco no se si te molesta

**Comment by nahytar** [comment]
actualice mi repositorio.
