### ISSUE TITLE
Subiendo cambios del acordeon

### ISSUE THREAD

**Issue by fannybecerravera** [fannybecerravera/scl-2018-05-bc-core-am-datadashboard#4]
Hola Mayra hay avance en el cambio del menú por el acordeón, el primer for si funciona es  el que al hacer click en la sede despliega las generaciones.
Lo que le falta es que veas en el data.js el segundo for para que funcione (que es el que al hacer click en generaciones despliega los turnos)
Cualquier cosa me escribes .

**Comment by nahytar** [comment]
hice funcionar el segundo for, también corregí la identación, arrow function, pseudo-variable this.
